/**
 * This code was generated by Builder.io.
 */
import React from "react";



const Footer = () => {
  return (
    <footer className="flex flex-col border-solid bg-primaryDark border-t-8 border-secondaryDark">
      <div className="mx-auto py-4 text-primaryLight">Insert Footer Here</div>
    </footer>
  );
};

export default Footer;