/**
 * This code was generated by Builder.io.
 */
import React from "react";



const Header = () => {
  return (
    <header className="flex flex-col border-solid bg-primaryDark border-t-8">
      <div className="mx-auto py-4 text-primaryLight">Insert Header Here</div>
    </header>
  );
};

export default Header;