/**
 * This code was generated by Builder.io.
 */
import React from "react";



function Header() {
  return (
    <header className="flex overflow-hidden flex-col self-stretch bg-primaryLight">
      <div className="flex flex-col items-start self-center w-full max-w-[1256px] max-md:max-w-full">
        <div className="flex flex-col justify-center py-3 w-full max-w-[1240px] max-md:max-w-full">
          <div className="flex flex-wrap justify-center items-center w-full max-w-[1262px] min-h-[120px] max-md:max-w-full">
            <div className="flex gap-10 self-stretch my-auto min-h-[120px] min-w-[240px]">
              <div className="flex items-start self-start w-[219px]">
                <div className="flex items-center w-[219px]">
                  <img loading="lazy" src="https://cdn.builder.io/api/v1/image/assets/TEMP/3969bd5d4349497c584720e34d92f1407f7ba54e6f90d3944a9e072675a4b199?placeholderIfAbsent=true&apiKey=7bf199de15724d268c1417f75ca31ce1" className="object-contain self-stretch my-auto aspect-[1.82] w-[219px]" alt="Company logo" />
                </div>
              </div>
              <img loading="lazy" src="https://cdn.builder.io/api/v1/image/assets/TEMP/d59d0da6242034294b6bd4de36e57a2b6fa067624185e39efe546882e91d64d4?placeholderIfAbsent=true&apiKey=7bf199de15724d268c1417f75ca31ce1" className="object-contain shrink-0 w-20 aspect-[0.67]" alt="Decorative element" />
            </div>
            <div className="flex flex-col self-stretch px-4 pt-4 pb-2 my-auto text-3xl tracking-tighter leading-none text-center text-black max-w-[631px] min-w-[240px] w-[631px] max-md:max-w-full">
              <h1 className="px-1.5 w-full max-md:max-w-full">
                <span>Breast & Ovarian Cancer Genetics</span>
              </h1>
            </div>
            <div className="flex flex-col flex-1 shrink self-stretch px-4 pt-4 my-auto text-center whitespace-nowrap basis-0 max-w-[316px] min-w-[240px]">
              <div className="flex gap-1 self-end max-w-full w-[174px]">
                {[...Array(4)].map((_, index) => (
                  <StatusBox key={`top-${index}`} textColor="text-blue-950" />
                ))}
              </div>
              <div className="flex items-start mt-2 w-full font-black">
                {[...Array(3)].map((_, index) => (
                  <StatusBox key={`bottom-${index}`} textColor="text-white" bgColor={index % 2 === 0 ? "text-orange-400" : "text-stone-600"} />
                ))}
              </div>
            </div>
          </div>
        </div>
      </div>
      <div className="flex w-full bg-orange-400 min-h-[2px] max-md:max-w-full" />
    </header>
  );
}

function StatusBox({ textColor, bgColor = "text-gray-50" }) {
  return (
    <div className="flex flex-1 items-center">
      <div className="flex flex-col self-stretch my-auto w-10">
        <div className={`px-1 text-3xl font-black leading-none ${bgColor}`}>
          {' '}
        </div>
        <div className={`z-10 px-3 -mt-8 text-base leading-8 ${textColor}`}>
          {' '}
        </div>
      </div>
    </div>
  );
}

export default Header;